service: bankfacilito
image: eduardogpg/bankfacilito

servers:
  - 147.182.131.19

proxy:
  app_port: 3000

registry:
  username: eduardogpg
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  local: true
  dockerfile: Dockerfile
  context: "."

env:
  secret:
    - RAILS_MASTER_KEY
